# Aluno: Estevão Holanda Lima Júnior
# Disciplina: Métodos Numéricos
# Curso: Engenharia de Computação
# Matricula: 201921250050

In [206]:
import numpy as np
import scipy.linalg as sla

In [207]:
def pivo(mE , i) :
    iMax = np.abs(mE[i : , i]).argmax() + i
    mE[[iMax, i]] = mE[[i, iMax]]
    return mE

def eliminacaoGaussiana(A, b) :
    mE = np.c_[A, b]
    n = len(A)
    
    for i in range(n - 1) :
        mE = pivo(mE, i)
        for j in range(i + 1, n) :
            mE[j] = mE[j] - (mE[j, i] / mE[i, i]) * mE[i]
    return mE[ : , : -1], mE[ : , -1]

def sist_lin_tri_sup(A, b) :
    n = len(b)
    x = np.zeros(n)
    x[-1] = b[-1] / A[-1, -1]
    for i in range(n - 2, -1, -1) :
        x[i] = (b[i] - np.sum(A[i, i + 1 :] * x[i + 1 :])) / A[i, i]
    return x

# a)

In [208]:
A1 = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]])
b1 = np.array([1, 2, 0])
A2, b2 = eliminacaoGaussiana(A1, b1)
sist_lin_tri_sup(A2, b2)

C:\Users\netom\AppData\Local\Temp\ipykernel_9976\4163232134.py:19: RuntimeWarning: invalid value encountered in long_scalars
  x[-1] = b[-1] / A[-1, -1]


array([nan, nan, nan])

In [209]:
sla.solve(A1, b1)

array([ 1., -1.,  1.])

# b)

In [210]:
A3 = np.array([[7, -7, 1], [-3, 3, 2], [7, 7, -72]])
b3 = np.array([1, 2, 7])
A4, b4 = eliminacaoGaussiana(A3, b3)
sist_lin_tri_sup(A4, b4)

array([5.64285714, 5.64285714, 1.        ])

In [211]:
sla.solve(A3, b3)

array([5.64285714, 5.64285714, 1.        ])

# c)

In [212]:
A5 = np.array([[1, 2, 3, 4], [2, 2, 3, 4], [3, 3, 3, 4], [4, 4, 4, 4]])
b5 = np.array([20, 22, 22, 24])
A6, b6 = eliminacaoGaussiana(A5, b5)
sist_lin_tri_sup(A6, b6)

array([ 2., -2.,  2.,  4.])

In [213]:
sla.solve(A5, b5)

array([ 2., -2.,  2.,  4.])