# Aluno: Estevão Holanda Lima Júnior
# Disciplina: Métodos Numéricos
# Curso: Engenharia de Computação
# Matricula: 201921250050

In [301]:
import numpy as np
import scipy.linalg as sla

# Exercício 1.1 Classifique os sistemas abaixo com relação a quantidade e existência de soluções.

In [302]:
A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b1 = np.array([1, 1, 1])

In [303]:
postoMC1 = np.linalg.matrix_rank(A1) # A
postoMC1

2

In [304]:
postoME1 = np.linalg.matrix_rank(np.c_[A1, b1]) # Ã
postoME1

2

# Resposta a): Sistema Possível Determinado

In [305]:
A2 = np.array([[2, 3], [-4, -6]])
b2 = np.array([10, -10])

In [306]:
postoMC2 = np.linalg.matrix_rank(A2) # A -> matriz de coeficientes
postoMC2

1

In [307]:
postoME2 = np.linalg.matrix_rank(np.c_[A2, b2]) # Ã -> matriz extendida
postoME2

2

# Resposta b): Sistema Impossível

# Exercício 1.2 Repita o exemplo 3.2 acima, porém fazendo cada passo da execução de forma explícita, comparando como o algoritmo 1.2 e a função sist_lin_tri_sup funcionam. Sugestão: faça isso de forma manuscrita. Ajudará a entender melhor cada passo.

In [308]:
A3 = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
b3 = np.array([-10, -1, 3, 2])

In [309]:
# Execução do passo a passo:

In [310]:
n = len(b3) # determinar o tamanho do array.
n

4

In [311]:
x = np.zeros(n) # criar um vetor de zeros.
x

array([0., 0., 0., 0.])

In [312]:
x[-1] = b3[-1] / A3[-1, -1] # calcular a icognita de maior índice.
x

array([0., 0., 0., 1.])

In [313]:
for i in range(n-2, -1, -1): # execução da substituição retroativa.
    print("Loop:", i)
    print("| b_i = ", b3[i], "| linhaI_Matriz = ", A3[i, i +1 : ], "| vetorResposta = ",x[i+1 : ], "| Icognita = ",x[i+1 : ])
    x[i] = (b3[i] - np.sum(A3[i, i +1 : ] * x[i+1 : ])) / A3[i,i]

Loop: 2
| b_i =  3 | linhaI_Matriz =  [-5] | vetorResposta =  [1.] | Icognita =  [1.]
Loop: 1
| b_i =  -1 | linhaI_Matriz =  [ 1 -2] | vetorResposta =  [2. 1.] | Icognita =  [2. 1.]
Loop: 0
| b_i =  -10 | linhaI_Matriz =  [ 4 -5  1] | vetorResposta =  [-1.  2.  1.] | Icognita =  [-1.  2.  1.]


In [314]:
x

array([ 1., -1.,  2.,  1.])

In [315]:
sla.solve_triangular(A3, b3, lower = False)

array([ 1., -1.,  2.,  1.])

# Exercício 1.3 Repita o exemplo 3.3 acima, porém fazendo cada passo da execução de forma explícita, comparando como o algoritmo 1.3 e a função sist_lin_tri_inf funcionam. Use a mesma sugestão do exercício anterior.

In [316]:
A4 = np.array([ [3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1] ])
b4 = np.array([4, 2, 4, 2])

In [317]:
n = len(b4)
n

4

In [318]:
x = np.zeros(n)
x

array([0., 0., 0., 0.])

In [319]:
x[0] = b4[0] / A4[0, 0]
x

array([1.33333333, 0.        , 0.        , 0.        ])

In [320]:
for i in range(1,n):
    print("Loop:", i)
    print("| b_i = ", b4[i], "| linhaI_Matriz = ", A4[i, : i], "| vetorResposta = ", x[ : i], "| Icognita = ", A4[i, i])
    x[i] = (b4[i] - np.sum(A4[i, : i] * x[ : i])) / A4[i, i]

Loop: 1
| b_i =  2 | linhaI_Matriz =  [2] | vetorResposta =  [1.33333333] | Icognita =  1
Loop: 2
| b_i =  4 | linhaI_Matriz =  [1 0] | vetorResposta =  [ 1.33333333 -0.66666667] | Icognita =  1
Loop: 3
| b_i =  2 | linhaI_Matriz =  [1 1 1] | vetorResposta =  [ 1.33333333 -0.66666667  2.66666667] | Icognita =  1


In [321]:
x

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

In [322]:
sla.solve_triangular(A4, b4, lower = True)

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])

# Implemente uma função, cujos parâmetros de entrada sejam somente a matriz de coeficientes e o vetor de termos independentes e que calcule o vetor solução para qualquer um dos casos triviais vistos aqui. Atente para o fato de que a própria função terá de verificar se a matriz de coeficientes é diagonal, triangular superior ou inferior e não o usuário.

In [323]:
def sist_lin_diagonal(A, b): 
    return b/A.diagonal()

In [324]:
m1 = np.diag([1, 4, 2])
v1 = np.array([4, 2, 2])
m2 = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
v2 = np.array([-10, -1, 3, 2])
m3 = np.array([ [3, 0, 0, 0], [2, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1] ])
v3 = np.array([4, 2, 4, 2])

In [325]:
def calcularCasoTrivial(mCoeficientes, vTermos):
    nLinhas = len(mCoeficientes)
    nColunas = len(mCoeficientes[0])
    
    matrizSup = True
    matrizInf = True

    for i in range(1, nLinhas):
        for j in range(0, i):
            if mCoeficientes[i][j] != 0:
                matrizSup = False
                
    for i in range(nLinhas):
        for j in range(i + 1, nColunas):
            if mCoeficientes[i][j] != 0:
                matrizInf = False
                
    if matrizSup and matrizInf:
        return sist_lin_diagonal(mCoeficientes, vTermos)
    elif matrizSup:
        return sla.solve_triangular(mCoeficientes, vTermos, lower = False)
    else:
       return sla.solve_triangular(mCoeficientes, vTermos, lower = True)


In [326]:
calcularCasoTrivial(m1, v1) # teste para matriz diagonal

array([4. , 0.5, 1. ])

In [327]:
calcularCasoTrivial(m2, v2) # teste para matriz triangular superior

array([ 1., -1.,  2.,  1.])

In [328]:
calcularCasoTrivial(m3, v3) # teste para matriz triangular inferior

array([ 1.33333333, -0.66666667,  2.66666667, -1.33333333])